// Generated by gencpp from file force_sensor/resetBiasRequest.msg
// DO NOT EDIT!


#ifndef FORCE_SENSOR_MESSAGE_RESETBIASREQUEST_H
#define FORCE_SENSOR_MESSAGE_RESETBIASREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace force_sensor
{
template <class ContainerAllocator>
struct resetBiasRequest_
{
  typedef resetBiasRequest_<ContainerAllocator> Type;

  resetBiasRequest_()
    : reset_bias_request(false)  {
    }
  resetBiasRequest_(const ContainerAllocator& _alloc)
    : reset_bias_request(false)  {
  (void)_alloc;
    }



   typedef uint8_t _reset_bias_request_type;
  _reset_bias_request_type reset_bias_request;





  typedef boost::shared_ptr< ::force_sensor::resetBiasRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::force_sensor::resetBiasRequest_<ContainerAllocator> const> ConstPtr;

}; // struct resetBiasRequest_

typedef ::force_sensor::resetBiasRequest_<std::allocator<void> > resetBiasRequest;

typedef boost::shared_ptr< ::force_sensor::resetBiasRequest > resetBiasRequestPtr;
typedef boost::shared_ptr< ::force_sensor::resetBiasRequest const> resetBiasRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::force_sensor::resetBiasRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::force_sensor::resetBiasRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::force_sensor::resetBiasRequest_<ContainerAllocator1> & lhs, const ::force_sensor::resetBiasRequest_<ContainerAllocator2> & rhs)
{
  return lhs.reset_bias_request == rhs.reset_bias_request;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::force_sensor::resetBiasRequest_<ContainerAllocator1> & lhs, const ::force_sensor::resetBiasRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace force_sensor

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::force_sensor::resetBiasRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::force_sensor::resetBiasRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::force_sensor::resetBiasRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::force_sensor::resetBiasRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::force_sensor::resetBiasRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::force_sensor::resetBiasRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::force_sensor::resetBiasRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f507d7cdfba8604617b8444600c62d63";
  }

  static const char* value(const ::force_sensor::resetBiasRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf507d7cdfba86046ULL;
  static const uint64_t static_value2 = 0x17b8444600c62d63ULL;
};

template<class ContainerAllocator>
struct DataType< ::force_sensor::resetBiasRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "force_sensor/resetBiasRequest";
  }

  static const char* value(const ::force_sensor::resetBiasRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::force_sensor::resetBiasRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool reset_bias_request\n"
;
  }

  static const char* value(const ::force_sensor::resetBiasRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::force_sensor::resetBiasRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.reset_bias_request);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct resetBiasRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::force_sensor::resetBiasRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::force_sensor::resetBiasRequest_<ContainerAllocator>& v)
  {
    s << indent << "reset_bias_request: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.reset_bias_request);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FORCE_SENSOR_MESSAGE_RESETBIASREQUEST_H
