// Generated by gencpp from file force_sensor/resetBias.msg
// DO NOT EDIT!


#ifndef FORCE_SENSOR_MESSAGE_RESETBIAS_H
#define FORCE_SENSOR_MESSAGE_RESETBIAS_H

#include <ros/service_traits.h>


#include <force_sensor/resetBiasRequest.h>
#include <force_sensor/resetBiasResponse.h>


namespace force_sensor
{

struct resetBias
{

typedef resetBiasRequest Request;
typedef resetBiasResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct resetBias
} // namespace force_sensor


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::force_sensor::resetBias > {
  static const char* value()
  {
    return "746b7f4e281851ca839750a1bcfc846b";
  }

  static const char* value(const ::force_sensor::resetBias&) { return value(); }
};

template<>
struct DataType< ::force_sensor::resetBias > {
  static const char* value()
  {
    return "force_sensor/resetBias";
  }

  static const char* value(const ::force_sensor::resetBias&) { return value(); }
};


// service_traits::MD5Sum< ::force_sensor::resetBiasRequest> should match
// service_traits::MD5Sum< ::force_sensor::resetBias >
template<>
struct MD5Sum< ::force_sensor::resetBiasRequest>
{
  static const char* value()
  {
    return MD5Sum< ::force_sensor::resetBias >::value();
  }
  static const char* value(const ::force_sensor::resetBiasRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::force_sensor::resetBiasRequest> should match
// service_traits::DataType< ::force_sensor::resetBias >
template<>
struct DataType< ::force_sensor::resetBiasRequest>
{
  static const char* value()
  {
    return DataType< ::force_sensor::resetBias >::value();
  }
  static const char* value(const ::force_sensor::resetBiasRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::force_sensor::resetBiasResponse> should match
// service_traits::MD5Sum< ::force_sensor::resetBias >
template<>
struct MD5Sum< ::force_sensor::resetBiasResponse>
{
  static const char* value()
  {
    return MD5Sum< ::force_sensor::resetBias >::value();
  }
  static const char* value(const ::force_sensor::resetBiasResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::force_sensor::resetBiasResponse> should match
// service_traits::DataType< ::force_sensor::resetBias >
template<>
struct DataType< ::force_sensor::resetBiasResponse>
{
  static const char* value()
  {
    return DataType< ::force_sensor::resetBias >::value();
  }
  static const char* value(const ::force_sensor::resetBiasResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FORCE_SENSOR_MESSAGE_RESETBIAS_H
